### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by why7e** [Cyber-Shadow/FalconsNest#10]
Because I'm too lazy to look back through commits to reply.

**Comment by Cyber-Shadow** [comment]
@Sir-Lagsalot  Which login page are you planning to use, i cannot tell...

**Comment by why7e** [comment]
Login.html

**Comment by why7e** [comment]
That's the one im working on. Made it to look like the impression.

**Comment by Cyber-Shadow** [comment]
Its not the same as the live website?

**Comment by Cyber-Shadow** [comment]
possible merging error

**Comment by Cyber-Shadow** [comment]
Also, feel free to remove the header

**Comment by why7e** [comment]
It's the same as my repo. Haven't done a push yet. I linked the site to my repo

**Comment by Cyber-Shadow** [comment]
I added the file

**Comment by why7e** [comment]
What file

**Comment by Cyber-Shadow** [comment]
login.html..
Answering your question...
You can make it not extend header.html, just remove this line: {% extends "webapp/header.html" %}

**Comment by Cyber-Shadow** [comment]
also, mobile compatibility isn't great right now.

**Comment by why7e** [comment]
Got rid of the header. Yeah, maybe instead of making the CSS in relation to %, I should to it using em.

**Comment by why7e** [comment]
Also used uptimerobot.com to stop my app from going to sleep.

**Comment by Cyber-Shadow** [comment]
@Sir-Lagsalot You should probably commit directly to the repository as merges are hit or miss

**Comment by why7e** [comment]
kk.

YESSS take a look at falconsnest.cf now

**Comment by why7e** [comment]
Ok. I dunno what's up. The heroku app is not registering the .logo css entry that I did, although my local one is.

**Comment by Cyber-Shadow** [comment]
@Sir-Lagsalot 
Nice, please make the background much lighter (or darker).
I will commit my working registration soon, gotta fix these conficts

**Comment by Cyber-Shadow** [comment]
100 commits now :+1:

**Comment by Cyber-Shadow** [comment]
@Sir-Lagsalot Your live website seems to be running off your repository, its somewhat behind and lacking the latest updates

**Comment by why7e** [comment]
Oh yeah, the Background's quite dark on my phone. I was messing with my GPU and now everything is brighter, so that looks normal to me.

Yeah it's based on my repo as I can't link yours, only my own repositries/forks.

Will merge asap.

**Comment by why7e** [comment]
How do I merge your commits to my fork on Android... Ugh

**Comment by why7e** [comment]
Why are we making a totally new page for an invalid login? Shouldnt we just get a pop-up or a <span>?

**Comment by Cyber-Shadow** [comment]
I was following a tutorial that suggests this, but django is flexible so we can do something else

**Comment by Cyber-Shadow** [comment]
@Sir-Lagsalot Please change the background colour of the website to #f2f2f2

**Comment by why7e** [comment]
Will do.

**Comment by hanyuone** [comment]
@Sir-Lagsalot @Cyber-Shadow 
Um... the login-invalid thing is broken. Is it possible to just tell me where it is and I'll fix it?

**Comment by why7e** [comment]
That's what I told him.

**Comment by hanyuone** [comment]
@Sir-Lagsalot I could try and fix it - I just don't know where it is. Is `invalid-login` a registration page or what?

**Comment by why7e** [comment]
Don't ask me, ask Creg. I just do the html/CSS. Are you using falconsnest.cf to test this or local server? Falconsnest.cf hasn't been merged with this repo yet.

**Comment by hanyuone** [comment]
@Sir-Lagsalot 
OK, sure.

NOTE: Accept my request on Skype!

**Comment by Cyber-Shadow** [comment]
@Sir-Lagsalot @DerpfacePython Hi, the issue was not mine... Your server is running outdated code :-1:

**Comment by Cyber-Shadow** [comment]
@Sir-Lagsalot 
Please stylise the register page, Add a registration link to the home page.
Also feel free to commit directly (please do). 
Please add me to the heroku group.

**Comment by why7e** [comment]
"Please stylise the register page, Add a registration link to the home page."
- I would like to, but I cannot create a pull request currently as our forks do not merge automatically. Could you take a look at this?

"Also feel free to commit directly (please do). "
- Dunno how

"Please add me to the heroku group."

Sure. Email?

**Comment by Cyber-Shadow** [comment]
hydrahead3355@gmail.com :)

**Comment by why7e** [comment]
Come on do something so I can help and make an excuse to not do hmwork ;~;
