### ISSUE TITLE
Ordering Plan

### ISSUE THREAD

**Issue by DirranShad** [Cyber-Shadow/FalconsNest#19]
### We've mostly finished the login, sign-up, etc, so we should start work on the whole point of the website.

Ordering.

Ofc, we would have some other features, and I thought that we could use this as a place to plan out what features we would have in terms of ordering.
I've thought of: Normal ordering, a "favourite order" (which might be used for something like a "quick order") and a set order for each day. (a schedule)
Anything else, comment and we can finalise all of what we will have for features.

We don't want the "no plan" like last time... :)

**Comment by why7e** [comment]
How bout a GUI for Chris to update and add new Menu items?

**Comment by Cyber-Shadow** [comment]
The canteen is becoming more and more unworth

**Comment by DirranShad** [comment]
Good Idea Gabe. 

We cant really change the _unworthness_ of the canteen...

**Comment by why7e** [comment]
How much are you going to bet that if Chris rolls this out, he'll up his prices? ^_^

**Comment by Cyber-Shadow** [comment]
lol

**Comment by DirranShad** [comment]
Oh and for the website, @Cyber-Shadow, instead of stealing a certain websites code, we could use this:
http://www.w3schools.com/howto/howto_css_icon_bar.asp#
http://www.w3schools.com/howto/howto_js_sidenav.asp 
A combination of the two or sth.

**Comment by why7e** [comment]
Maybe instead of a header bar we could make a collapsible popup tab on the side of the screen expands and collapses into that icon bar?

**Comment by DirranShad** [comment]
Craig said that we were ditching the idea of a header bar and (not) steal skedular's bar.

**Comment by why7e** [comment]
Schedular bar is good ;~; we can just rescheme the colors, then it will have that Falcon feeling

**Comment by DirranShad** [comment]
![side bar](https://cloud.githubusercontent.com/assets/19743180/17081245/23fa233c-5194-11e6-80ac-71518720ec9f.png)
I was thinking something like this.
Changing the colour scheme around would help a lot however.

**Comment by why7e** [comment]
Having all the functionality of a webpage clumped together into a single dropdown? Isn't that simplicity of?

**Comment by DirranShad** [comment]
i see what you mean

**Comment by DirranShad** [comment]
But Its basically what skedular does..

**Comment by DirranShad** [comment]
Instead of words, icons.
_Thats what I trying to do_

**Comment by why7e** [comment]
[This comment has been removed.]
Reason: No weebly, please.

**Comment by DirranShad** [comment]
pls no
![side bar2](https://cloud.githubusercontent.com/assets/19743180/17081285/61f87368-5195-11e6-803b-b9e6bcc5be6c.png)

**Comment by hanyuone** [comment]
@Sir-Lagsalot Why is there C and TCL? Just curious.

**Comment by DirranShad** [comment]
And that bar will slide out and back in.
All open for ideas though

**Comment by why7e** [comment]
@derpfacepython

What C? Tcl is from virtuenv, heroku requires it.

**Comment by Cyber-Shadow** [comment]
Just click on tcl to find out.

**Comment by why7e** [comment]
Don't see what's wrong.

Haha lol went onto the hanyuan page and used 6mb of data... Shit.

**Comment by Cyber-Shadow** [comment]
Dylan is a frikn legend

**Comment by why7e** [comment]
Yes bruh. Put in an autoplay 1080p video in the background to eat more data

**Comment by DirranShad** [comment]
Lol rip load times.

**Comment by DirranShad** [comment]
Back to the ordering plan however, any other ideas for how to order in different ways?
Or ways for design.
If not, we can get to making the website.

**Comment by why7e** [comment]
Maybe a slideshow at the top,?
A bunch of buttons that redirect to certain food categories? (Instant noodles, etc)
Maybe a search bar?
List by (Unhealthiness, price, alphabetical, etc) :

**Comment by DirranShad** [comment]
Unhealthiness.... LOL

**Comment by why7e** [comment]
Shit got real

**Comment by why7e** [comment]
So I was thinking of the login bar being something like the Chrome "inspect element" tool, where when you type something in, it will come up with the ~5 most relevant items. 

We could expand on this by making it expand into a short description and image. 

How about that? Too hard?

**Comment by DirranShad** [comment]
Creg, you made a new file for Chris, does that mean we can do student ordering on your nest now?

**Comment by DirranShad** [comment]
If you dont get what I mean, skype meh

**Comment by hanyuone** [comment]
I can add a JS thing so it records prices and makes a receipt thing.

**Comment by hanyuone** [comment]
Stuff that should be in the sidebar (or someplace else, whatever):
- Types of foods          -_We can just have a menu instead of separate menus._
  - Burgers
  - Wraps
  - Other foods
- Types of "ordering", whatever that means
  - Schedule of ordering

Other stuff:
- Sort by price
- Sort by recently ordered
- Randomiser?               -_Nah_
  Click on profile:
- Settings? 
  - Personal colour scheme?            -_Skedular Style_

**Comment by DirranShad** [comment]
We've planned this all out and finally know what to do.

I'm going to close this issue now.
