### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by carey-li** [Cyber-Shadow/FalconsNest#2]
Why do you need this, we already pretty much have an ordering system i.e. going at recess to order. Chris is not likely going to be able to use this as well.

**Comment by Cyber-Shadow** [comment]
Thanks for your concern, but Chris has asked some seniors (i.e. Chen and Ben) to do this. We are carrying on this project. Even if there is no benefit for the school (If our project is rejected), it will benefit our skills.

**Comment by carey-li** [comment]
If you want to benefit your skills, do a MOOC course. Knowledge on
algorithms will help you more than php, HTML and mysql.

**Comment by Cyber-Shadow** [comment]
Need I say it again? The canteen staff have requested this to be done.

**Comment by carey-li** [comment]
Need you develop your English? I was addressing your comment on developing
your skills.

**Comment by Cyber-Shadow** [comment]
Well thank your for your input, I guess.
