### ISSUE TITLE
Animated sidebar broken (Again!!)

### ISSUE THREAD

**Issue by Cyber-Shadow** [Cyber-Shadow/FalconsNest#26]

**Comment by why7e** [comment]
No i just haven't pushed

**Comment by why7e** [comment]
Give me time to kick my bro off

**Comment by DirranShad** [comment]
What was the problem?

**Comment by Cyber-Shadow** [comment]
~~Seems that some of hanyuan's updates broke the header,
there is a working version here:
https://github.com/Cyber-Shadow/FalconsNest/commits/ca98b74092edfd5b3fcf8c612575e0d1feb1ebfe.~~

Edit: NVM this was fixed but gabe broke it again :(
