### ISSUE TITLE
List of stuff to work on:

### ISSUE THREAD

**Issue by Cyber-Shadow** [Cyber-Shadow/FalconsNest#27]
-Submission box for ordering.
-Optimise the header and sidebar. _-Lets make the page shift "onclick" as well as getting rid of the logged in as thing "onclick"_
-Ordering and self sustaining environment for chris
-Stylise Unauthorised page.
-Stylise 404, 403 pages.

Submit extra things to work on.

**Comment by Cyber-Shadow** [comment]
~~@DirranShad Mobile compatibility for the settings...~~

_Done and dusted as well as full compatibility with the header._

**Comment by DirranShad** [comment]
I finished it but bitdefender crashed the party ;(

**Comment by DirranShad** [comment]
I have a backup tho, will commit from onedrive when I can
